apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: todo
  name: my
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: quay.io/burrsutter/todo:9.0.0
        env:
        - name: QUARKUS_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/postgresdb
        - name: QUARKUS_DATASOURCE_USERNAME
          value: admin
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: adminS3cret
        - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
          value: none
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "60Mi" 
            cpu: "100m" 
          limits:
            memory: "60Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            port: 8080
            path: /hello
          initialDelaySeconds: 2
          periodSeconds: 3

